### ISSUE TITLE
consider phpstan ^0.11

### ISSUE THREAD

**Issue by sasezaki** [bearsunday/BEAR.QATools#14]
please add!

**Comment by koriym** [comment]
Good idea. PR, please !

**Comment by sasezaki** [comment]
Do you have any approach to check to keep depedency  latest version on CI?

**Comment by koriym** [comment]
Nope

**Comment by koriym** [comment]
https://github.com/kubawerlos/composer-json-fixer

This package works fine.

**Comment by koriym** [comment]
Released https://github.com/bearsunday/BEAR.QATools/releases/tag/1.9.3

**Comment by koriym** [comment]
@sasezaki changed to version `^0.10` to `~0.10` in 1.9.5.
The latest version is available with this constrain.

https://github.com/bearsunday/BEAR.QATools/releases/tag/1.9.5
