### ISSUE TITLE
composer install 時に warning (sebastian/git abandoned)

### ISSUE THREAD

**Issue by madapaja** [bearsunday/BEAR.QATools#4]
phploc 3.x が依存している `sebastian/git` ( https://github.com/sebastianbergmann/git )が abandoned なため、composer install 時に warning が出ます。

phploc 4.x で `sebastian/git` への依存が無くなっているため、そちらへのアップデートがいいかもしれません。
https://github.com/sebastianbergmann/phploc/blob/master/composer.json

**Comment by koriym** [comment]
なるほど、ありがとうございます（返信遅れてすいません）
PR頂ければと！
